name: PR-CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate-goreleaser:
    name: Validate .goreleaser.yml
    runs-on: ubuntu-latest

    steps:
      - name: setup
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - name: Check out repositories
        id: checkout
        uses: actions/checkout@v2

      - name: Validate .goreleaser.yml with goreleaser-action
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --snapshot --skip-publish --rm-dist --debug